### ISSUE TITLE
cannot create new Action

### ISSUE THREAD

**Issue by MrThiemann** [devcybiko/ses-catchall#1]
Hey,
first of all thanks for this Git!!

...but i have a question....

In Amazon SES --> Configuration: Email receiving --> INBOUND_MAIL --> m-71c29loremipsum
i cannot create an new Action. Only i can edit the action type: Integrate with Amazon WorkMail

When i open it, then i can create a new action. but I don't know exactly what to select here.
![Bildschirmfoto 2022-08-11 um 07 59 03](https://user-images.githubusercontent.com/54147030/184072828-bbd67ab0-a066-400a-93b0-24edf82bab07.png)
![Bildschirmfoto 2022-08-11 um 07 59 13](https://user-images.githubusercontent.com/54147030/184072840-fb12c36a-7e59-443e-9157-ee1e74303d33.png)

can you help me? thank you =)

**Comment by devcybiko** [comment]
which step is this? I don't recognize it.

On Aug 11, 2022, at 2:01 AM, MrThiemann ***@***.*** ***@***.***> > wrote:


Hey,
first of all thanks for this Git!!

...but i have a question....

In Amazon SES --> Configuration: Email receiving --> INBOUND_MAIL --> m-71c29loremipsum
i cannot create an new Action. Only i can edit the action type: Integrate with Amazon WorkMail

When i open it, then i can create a new action. but I don't know exactly what to select here.
 <https://user-images.githubusercontent.com/54147030/184072828-bbd67ab0-a066-400a-93b0-24edf82bab07.png> 
 <https://user-images.githubusercontent.com/54147030/184072840-fb12c36a-7e59-443e-9157-ee1e74303d33.png> 

can you help me? thank you =)

**Comment by MrThiemann** [comment]
This is the SES SETUP

**Comment by devcybiko** [comment]
overcome by events.
