### ISSUE TITLE
SNS Setup

### ISSUE THREAD

**Issue by MrThiemann** [devcybiko/ses-catchall#2]
Hey,
is the code correct from the SNS-Setup? --> https://github.com/devcybiko/ses-catchall#sns-setup

When i copy & paste it, i became an error.

Thank you =)

**Comment by devcybiko** [comment]
In that case you just need to add the one line to the policy... the code displayed is an example

*	add "Service": "ses.amazonaws.com <http://ses.amazonaws.com> ", to the Statement.Principal JSON object

On Aug 11, 2022, at 2:48 AM, MrThiemann ***@***.*** ***@***.***> > wrote:


Hey,
is the code correct from the SNS-Setup? --> https://github.com/devcybiko/ses-catchall#sns-setup <https://github.com/devcybiko/ses-catchall#sns-setup> 

When i copy & paste it, i became an error.

Thank you =)

**Comment by MrThiemann** [comment]
Hey Greg, thank you for your answer!

Am I right here?
![Bildschirmfoto 2022-08-11 um 16 49 07](https://user-images.githubusercontent.com/54147030/184162475-a70ace4b-b68b-461b-b144-152b577a3aac.png)

**Comment by devcybiko** [comment]
Closing Overcome by events.
